[manifest]
version = "1.0.0"
priority = 0

[[patches]]
[patches.pattern]
target = "game.lua"
position = "before"
pattern = "for _, v in ipairs(self.FONTS) do"
payload = """
_tokipona_init_language(self)
"""
times = 1
match_indent = true

[[patches]]
[patches.pattern]
target = "main.lua"
position = "before"
pattern = "function love.run()"
payload = '''
_tokipona_load_language("{{lovely_hack:patch_dir}}")
'''
times = 1
match_indent = true

[[patches]]
[patches.copy]
target = "main.lua"
position = "prepend"
sources = ["patch.lua"]

# Retrigger color

[[patches]]
[patches.pattern]
target = "functions/misc_functions.lua"
position = "after"
pattern = "dark_edition = G.C.DARK_EDITION,"
payload = """
retrigger = G.C.RETRIGGER,
"""
times = 1
match_indent = true

[[patches]]
[patches.pattern]
target = "globals.lua"
position = "after"
pattern = "ETERNAL = HEX('c75985'),"
payload = """
RETRIGGER = HEX('30c0e0'),
"""
times = 1
match_indent = true

# nativefs

[[patches]]
[patches.module]
source = "nativefs.lua"
before = "main.lua"
name = "nativefs" 

# round score fix

[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
position = "at"
pattern = "{n=G.UIT.T, config={text = localize('k_round'), scale = 0.42, colour = G.C.UI.TEXT_LIGHT, shadow = true}}"
payload = """
{n=G.UIT.T, config={text = (localize('k_upper_score') ~= "ERROR" and localize('k_upper_score')) or localize('k_round'), scale = 0.42, colour = G.C.UI.TEXT_LIGHT, shadow = true}}
"""
times = 1
match_indent = true
